### ISSUE TITLE
[FEATURE] add possibility to play .wav files

### ISSUE THREAD

**Issue by Pauler221** [AkaneTan/Symphonica#15]
First of all thank you for an awesome music player! I really enjoy it!

It would be really convenient if you'd add the possibility to play .wav files and preferably other formats as well like .ogg etc.

**Comment by AkaneTan** [comment]
Ah yes, thanks for your request! Tho symphonica soon will be archived since I'm baking a new project from the ground now. Maybe you can cope with the current version and wait till https://github.com/AkaneTan/Gramophone is released? I will surely add your requested feature in gramophone's future version.
